import = [
    "~/.config/alacritty/themes/themes/ayu_dark.toml"
]

[window]
opacity = 0.95

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 14

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

