[pyprland]
plugins = [
  "scratchpads",
  # "lost_windows",
  # "monitors",
  # "toggle_dpms",
  # "magnify",
  # "expose",
  # "shift_monitors",
  # "workspaces_follow_focus",
]

[workspaces_follow_focus]
max_workspaces = 9

[expose]
include_special = false

[scratchpads.stb]
animation = "fromBottom"
command = "alacritty --class alacritty-stb sstb"
class = "alacritty-stb"
lazy = true
size = "75% 45%"

[scratchpads.stb-logs]
animation = "fromTop"
command = "alacritty --class alacritty-stb-logs stbLog"
class = "alacritty-stb-logs"
lazy = true
size = "75% 40%"

[scratchpads.term]
animation = "fromTop"
command = "alacritty --class alacritty-dropterm"
class = "alacritty-dropterm"
size = "75% 60%"

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "pavucontrol"
lazy = true
size = "40% 90%"
unfocus = "hide"

[monitors]
unknown = "wlrlui"

[monitors.placement]
"Sony".top_of = ["Brand X", "Other Brand"]
"Acer".left_end_of = "Sony"
"MSI Gaming stuff".bottom_center_of = "(HDMI-A-1)"
